spring:
  kafka:
    bootstrap-servers: kafkahost:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        session.timeout.ms: 15000

  redis:
    database: 0
    host: 192.168.89.121
    port: 6379
    key-prefix: p809_    #在Redis里上级平台key的前缀
    lettuce:
      shutdown-timeout: 3000

kafka-topics:
  inbound-msg:
    group-id: gateway809
    topic-name: inbound-msg
  inbound-msg-location:
    group-id: gateway809location
    topic-name: inbound-msg-location
  outbound-msg:
    group-id: gateway809
    topic-name: outbound-msg
  change-notice:
    group-id: gateway809
    topic-name: change-notice


